export { default as compose } from './compose'
export { default as Maybe } from './maybe'
export { default as rcompose } from './rcompose'
export { default as uncurry } from './uncurry'
export { default as identity } from './identity'
export { default as flip } from './flip'
export * from './either'
